version: "3.8"

services:
  buyer_service:
    build: ./BuyerService
    stdin_open: true
    tty: true
    depends_on:
      - buyer_db
    ports:
      - 0.0.0.0:8002:8002
    networks:
      - storenet
      - buyernet  

  buyers_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buyers
    ports:
      - 5432:5432
    volumes:
      - buyers-db_data:/var/lib/postgres/data
      - ./BuyerDb:/docker-entrypoint-initdb.d/
    networks:
      - buyernet

networks:
  storenet:
    driver: bridge

  buyernet:
    driver: bridge

volumes:
  buyers-db_data:
  buyer_service:
