version: "3.8"

services:
  buyer_service:
    build: ./BuyerService
    stdin_open: true
    tty: true
    depends_on:
      - buyers_db
    ports:
      - 0.0.0.0:8002:8002
    networks:
      - storenet
      - buyernet

  buyers_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buyers
    volumes:
      - buyers-db_data:/var/lib/postgres/data
      - ./BuyerDb:/docker-entrypoint-initdb.d/
    networks:
      - buyernet

  merchant_service:
    build: ./MerchantService
    stdin_open: true
    tty: true
    depends_on:
      - merchant_db
    ports:
      - 0.0.0.0:8001:8001
    networks:
      - storenet
      - merchantnet

  merchant_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=merchants
    volumes:
      - merchant-db_data:/var/lib/postgres/data
      - ./MerchantDb:/docker-entrypoint-initdb.d/
    networks:
      - merchantnet

  inventory_service:
    build: ./InventoryService
    stdin_open: true
    tty: true
    depends_on:
      - inventory_db
    ports:
      - 0.0.0.0:8003:8003
    networks:
      - storenet
      - inventorynet

  inventory_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory
    volumes:
      - inventory-db_data:/var/lib/postgres/data
      - ./InventoryDb:/docker-entrypoint-initdb.d/
    networks:
      - inventorynet

  order_service:
    build: ./OrderService
    stdin_open: true
    tty: true
    depends_on:
      - order_db
      - rabbitmq
    ports:
      - 0.0.0.0:8000:8000
    networks:
      - storenet
      - ordernet

  order_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    volumes:
      - order-db_data:/var/lib/postgres/data
      - ./OrderDb:/docker-entrypoint-initdb.d/
    networks:
      - ordernet

  payment_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments
    volumes:
      - payment-db_data:/var/lib/postgres/data
      - ./PaymentDb:/docker-entrypoint-initdb.d/
    networks:
      - payment_net

  payment_service:
    build: ./PaymentService
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
    networks:
      - storenet
      - payment_net

  email_service:
    build: ./EmailService
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
    networks:
      - storenet
      - emailnet

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      name: "rabbitmq1"
    networks:
      - storenet

networks:
  storenet:
    driver: bridge

  buyernet:
    driver: bridge

  merchantnet:
    driver: bridge

  ordernet:
    driver: bridge

  inventorynet:
    driver: bridge

  payment_net:
    driver: bridge

  emailnet:
    driver: bridge

volumes:
  payment_service:
  payment-db_data:
  rabbitmq:
  order-db_data:
  order_service:
  merchant-db_data:
  merchant_service:
  buyers-db_data:
  buyer_service:
  inventory_service:
  inventory-db_data:
  email_service:
